const $=id=>document.getElementById(id);
const advisors=[['ceo','経営参謀','全社方針・優先順位','目的、制約、引き返せる条件を整理する。'],['sales','営業参謀','顧客・価格・提案','顧客価値と採算、継続取引の条件を確認する。'],['finance','財務参謀','資金・利益・投資','固定費の増加と手元資金への影響を確認する。'],['people','組織参謀','採用・配置・育成','担当者の負荷、育成の余力、役割の明確さを確認する。'],['business','事業参謀','実行・業務・進捗','実行体制を整え、担当と確認期限を決める。']];
const questions=['あなたが人生・仕事で一貫して追っている「テーマ」は何ですか？','どんな状況でも守りたい原則を5つ挙げてください。','成果が出ても「これだけはやらない」ことを5つ挙げてください。','迷った時の最終判断ルールを1〜3本、教えてください。','価値観が衝突した時、最終的に優先する順番は何ですか？','人間関係で最重要なこと3つ／絶対に許せないこと3つは何ですか？','自分を好きでいられる状態／自分が嫌いになる状態はどんな時ですか？','責任を持ちたい相手は誰ですか？その人たちへの約束は何ですか？','あなたの成功を数値なしで定義すると、何ですか？','人生観を決定づけた出来事・人物・作品を3つ挙げ、それぞれの教訓を教えてください。'];
const roleQuestions={ceo:'部門ごとの最適と会社全体の最適が衝突した時、どう決めますか？',finance:'成長投資と資金の安全性が衝突した時、何を条件に判断しますか？',business:'品質・納期・コストが衝突した時、何を優先しますか？',sales:'売上・利益・顧客との関係が衝突した時、何を守りますか？',people:'短期の成果と社員の育成が衝突した時、どう判断しますか？'};
let selected='ceo',profile=null,activeTopic='',activeAdvisors=[],logs=[],roleAnswers={};
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function page(name){for(const id of ['team','profile','decisions'])$(id).hidden=id!==name;document.querySelectorAll('[data-page]').forEach(b=>{if(b.dataset.page===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(name==='decisions')renderLogs();}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function renderAdvisors(){const container=$('advisors');container.replaceChildren();advisors.forEach(([id,name,detail],i)=>{const b=element('button',undefined,'advisor');b.type='button';b.setAttribute('aria-pressed',String(id===selected));b.append(element('span','0'+(i+1),'number'),element('strong',name),element('small',detail));b.onclick=()=>{selected=id;$('selected-role').textContent=name+'に相談';renderAdvisors()};container.append(b)});}
questions.forEach((text,i)=>{const d=element('div',undefined,'question');const l=element('label','Q'+(i+1)+'　'+text);l.htmlFor='q'+i;const a=element('textarea');a.id='q'+i;d.append(l,a);$('questions').append(d)});
function renderRole(){const id=$('executive-role').value;const d=$('role-question');d.replaceChildren();const l=element('label',roleQuestions[id]);l.htmlFor='role-answer';const a=element('textarea');a.id='role-answer';a.value=roleAnswers[id]||'';a.oninput=()=>roleAnswers[id]=a.value;d.append(l,a)}
$('executive-role').onchange=renderRole;
$('profile-form').onsubmit=e=>{e.preventDefault();profile={company:$('company').value.trim(),policy:$('policy').value.trim(),role:$('executive-role').value,answers:questions.map((_,i)=>$('q'+i).value.trim()),roleAnswer:$('role-answer').value.trim()};$('profile-status').textContent='このタブ内に保存しました。';};
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('topic').value=b.dataset.example});
$('consult').onclick=()=>{activeTopic=$('topic').value.trim();if(!activeTopic){$('notice').textContent='相談内容を入力してください。';return}$('notice').textContent='';activeAdvisors=$('meeting').checked?advisors:advisors.filter(a=>a[0]===selected);$('responses').replaceChildren();activeAdvisors.forEach(([id,name,detail,advice])=>{const d=element('article',undefined,'advice');d.append(element('h3',name),element('p',advice));const p=element('p',undefined,'source');p.textContent='必要な情報：'+({ceo:'目的・期限・承認者',sales:'顧客の要望・原価・契約条件',finance:'手元資金・収支・追加費用',people:'現在の負荷・採用要件・育成担当',business:'業務量・担当・期限'}[id]);d.append(p);$('responses').append(d)});if($('meeting').checked){const d=element('article',undefined,'advice');d.append(element('h3','参謀会議のまとめ'),element('p','一致点：目的と必要な情報を先に整理する。対立点：成長の機会と固定費・現場負荷のバランス。まず小さく試せる条件を検討する。'));$('responses').append(d)}if(profile){const d=element('article',undefined,'advice');d.append(element('h3','本人と会社の判断軸（登録内容）'),element('p','本人の判断ルール：'+(profile.answers[3]||'未登録')),element('p','会社の方針：'+(profile.policy||'未登録')),element('p','登録内容を表示しています。サンプル回答への自動反映は未実装です。','source'));$('responses').append(d)}$('draft').textContent='検討メモ（下書き）\n\n相談：'+activeTopic+'\n\n目的：［記入］\n選択肢：今実行する／小さく試す／追加情報を待つ\n必要な情報：［確認する数値・条件を記入］\n担当：［記入］\n確認期限：［記入］\n見直す条件：［記入］';$('decision').value='';$('response').hidden=false;$('empty').hidden=true;};
$('record').onclick=()=>{const text=$('decision').value.trim();if(!text){$('notice').textContent='決定と理由を入力してください。';$('decision').focus();return}logs.unshift({topic:activeTopic,text,advisors:activeAdvisors.map(a=>a[1]),date:new Date().toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})});page('decisions')};
function renderLogs(){const list=$('decision-list');list.replaceChildren();if(!logs.length){list.append(element('div','まだ記録がありません。参謀への相談後に、決定と理由を残せます。','panel'));return}logs.forEach(log=>{const d=element('article',undefined,'panel');d.append(element('h2',log.topic),element('p',log.text,'decision-text'),element('small',log.date+' · '+log.advisors.join('・')));list.append(d)})}
renderAdvisors();renderRole();
